<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>$(MSBuildProjectName.Replace("-dev", ""))</AssemblyName>
    <RootNamespace>$(MSBuildProjectName.Replace("-dev", ""))</RootNamespace>
  </PropertyGroup>

</Project>
